#!/bin/bash

# check argc
if [ "$#" -ne 1 ]; then
    echo "Usage: breaches_per_month [filename]" > "/dev/stderr"
    exit 1
fi

# check if input file exists
if [[ ! -f $1 ]]; then
    echo "Error: File does not exist or is zero-length" > "/dev/stderr"
    exit 1
fi


cut -f6 "$1" | sort | uniq -c | sort -k2n | awk '{print}' | sed '1d' | awk ' {
    FS=OFS=" "
    split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec", months, " ")
    month = $(2)
    $(2) = months[month]
} 1' | awk '{
        temp = $1
        $1 = $2
        $2 = temp
        print > "almostdone.txt"
    }' 

sort -k2n almostdone.txt | awk '{print}' | awk ' {
    data[NR-1] = $2
    months[NR-1] = $1
} END {
    total = 0
    for(i=0;i<12;i++)
        total += data[i]

    #for(i=0;i<12;i++)
    #    print data[i], months[i]

    #print "total is: " total
    median = (data[5] + data[6])/2
    print median

    for(i=0;i<12;i++) {
        value = data[i] - median
        new = value
        if (value < 0)
            meddata[i] = value * -1
        else
            meddata[i] = value
        print meddata[i]
    }

    #MAD = (meddata[5] + meddata[6])/2
    #print "MAD is " MAD
}' almostdone.txt > meddata.txt

cut -f 1 meddata.txt | head -n 1 | awk '{print}' > median.txt
median=$(cat median.txt)

sed -i '1d' meddata.txt

sort -k1n meddata.txt | awk '{print}' | awk ' {
    data[NR-1] = $1
} END {
    MAD = (data[5] + data[6])/2
    print MAD > "MAD.txt"
}' 

MAD=$(cat MAD.txt)

echo $median $MAD > "/dev/stdout"

awk -v MAD="$MAD" -v median="$median" ' {
    months[NR-1] = $1
    data[NR-1] = $2
} END {
    for(i=0;i<12;i++) {
        diff = (data[i]-median)
        if (diff < (MAD * (-1) ) )
            print months[i],data[i],"--"
        else if (diff <= MAD )
            print months[i],data[i]
        else
            print months[i],data[i],"++"
    }
}' almostdone.txt > output.txt

echo $(cat output.txt) > "/dev/stdout"

rm MAD.txt meddata.txt median.txt output.txt almostdone.txt


exit 0