#!/bin/bash

# check argc
if [ "$#" -ne 1 ]; then
    echo "Usage: breaches_per_month [filename]" > "/dev/stderr"
    exit 1
fi

# check if input file exists
if [[ ! -f $1 ]]; then
    echo "Error: File does not exist or is zero-length" > "/dev/stderr"
    exit 1
fi

# Returns a space separated set of month and number of breaches
cut -f6 "$1" | sort | uniq -c | sort -k2n | awk '{print}' | sed '1d' | awk ' {
    FS=OFS=" "
    split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec", months, " ")
    month = $(2)
    $(2) = months[month]
} 1' | awk '{
        temp = $1
        $1 = $2
        $2 = temp
        print > "splitData.txt"
    }' 


# Returns the median of the dataset, then after that space separated month subtract median (month-median)
sort -k2n splitData.txt | awk '{print}' | awk ' {
    data[NR-1] = $2
    months[NR-1] = $1
} END {
    total = 0
    for(i=0;i<12;i++)
        total += data[i]

    #for(i=0;i<12;i++)
    #    print data[i], months[i]

    #print "total is: " total
    median = (data[5] + data[6])/2
    print median

    for(i=0;i<12;i++) {
        value = data[i] - median
        new = value
        if (value < 0)
            monthMedians[i] = value * -1
        else
            monthMedians[i] = value
        print monthMedians[i]
    }

    #MAD = (monthMedians[5] + monthMedians[6])/2
    #print "MAD is " MAD
}' splitData.txt > monthMedians.txt


# Retrieving the median from the monthMedians file
cut -f 1 monthMedians.txt | head -n 1 | awk '{print}' > median.txt
median=$(cat median.txt)

# Removing the overall median so monthMedians is just the month-medians
sed -i '1d' monthMedians.txt

# Returning the MAD by getting the median of that data set
sort -k1n monthMedians.txt | awk '{print}' | awk ' {
    data[NR-1] = $1
} END {
    MAD = (data[5] + data[6])/2
    print MAD > "MAD.txt"
}' 

MAD=$(cat MAD.txt)


echo "Median: " $median " MAD: " $MAD > "medianMADoutput.txt"

awk -v MAD="$MAD" -v median="$median" ' {
    months[NR-1] = $1
    data[NR-1] = $2
} END {
    for(i=0;i<12;i++) {
        diff = (data[i]-median)
        if (diff < (MAD * (-1) ) )
            print months[i],data[i],"--"
        else if (diff <= MAD )
            print months[i],data[i]
        else
            print months[i],data[i],"++"
    }
}' splitData.txt > outputData.txt

awk '{print}' medianMADoutput.txt outputData.txt  > "/dev/stdout"

rm MAD.txt monthMedians.txt median.txt outputData.txt splitData.txt medianMADoutput.txt

exit 0